players:
  player1:
    controls:
      left: VK_LEFT
      right: VK_RIGHT
      up: VK_UP
      down: VK_DOWN
  player2:
    controls:
      left: VK_A
      right: VK_D
      up: VK_W
      down: VK_S

